"""empty message

Revision ID: 1ab096ec8104
Revises: None
Create Date: 2015-09-17 23:41:35.981020

"""

# revision identifiers, used by Alembic.
revision = '1ab096ec8104'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componentCPI',
    sa.Column('component', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cpi_jan', sa.Integer(), nullable=True),
    sa.Column('cpi_feb', sa.Integer(), nullable=True),
    sa.Column('cpi_march', sa.Integer(), nullable=True),
    sa.Column('cpi_april', sa.Integer(), nullable=True),
    sa.Column('cpi_may', sa.Integer(), nullable=True),
    sa.Column('cpi_june', sa.Integer(), nullable=True),
    sa.Column('cpi_aug', sa.Integer(), nullable=True),
    sa.Column('cpi_sept', sa.Integer(), nullable=True),
    sa.Column('cpi_oct', sa.Integer(), nullable=True),
    sa.Column('cpi_nov', sa.Integer(), nullable=True),
    sa.Column('cpi_dec', sa.Integer(), nullable=True),
    sa.Column('cpi_u_half1', sa.Integer(), nullable=True),
    sa.Column('cpi_u_half2', sa.Integer(), nullable=True),
    sa.Column('cpi_u_annual', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('component', 'year')
    )
    op.create_table('userEntry',
    sa.Column('entryID', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('cpi_u', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('entryID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userComponent',
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('entryID', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entryID'], ['userEntry.entryID'], ),
    sa.PrimaryKeyConstraint('component')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('userComponent')
    op.drop_table('users')
    op.drop_table('userEntry')
    op.drop_table('componentCPI')
    ### end Alembic commands ###
