"""empty message

Revision ID: 26b2c1070579
Revises: 1ab096ec8104
Create Date: 2015-09-20 21:38:58.637942

"""

# revision identifiers, used by Alembic.
revision = '26b2c1070579'
down_revision = '1ab096ec8104'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
