"""empty message

Revision ID: 2b5076e84553
Revises: 26b2c1070579
Create Date: 2015-09-20 21:40:43.441419

"""

# revision identifiers, used by Alembic.
revision = '2b5076e84553'
down_revision = '26b2c1070579'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
