"""empty message

Revision ID: 51be0587bfa5
Revises: 2b5076e84553
Create Date: 2015-09-20 21:55:46.046462

"""

# revision identifiers, used by Alembic.
revision = '51be0587bfa5'
down_revision = '2b5076e84553'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
